//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BANK
    {
        public BANK()
        {
            this.PAYMENT = new HashSet<PAYMENT>();
        }
    
        public string BnkAccNumber { get; set; }
        public string BnkName { get; set; }
        public string BnkConName { get; set; }
        public string BnkEnabled { get; set; }
    
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
    }
}
