//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRAND
    {
        public BRAND()
        {
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public string BrandID { get; set; }
        public string BrandName { get; set; }
        public string TrdID { get; set; }
        public string BrandEnabled { get; set; }
    
        public virtual TRADEMARK TRADEMARK { get; set; }
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}
