//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIMORDER_DTA
    {
        public CLAIMORDER_DTA()
        {
            this.RECEIVECLAIM_DTA = new HashSet<RECEIVECLAIM_DTA>();
            this.CLAIM_MEMBER_DTA = new HashSet<CLAIM_MEMBER_DTA>();
            this.SERIAL = new HashSet<SERIAL>();
        }
    
        public string ClmID { get; set; }
        public string ClmNo { get; set; }
    
        public virtual CLAIMORDER CLAIMORDER { get; set; }
        public virtual CLAIMORDER_SHOP CLAIMORDER_SHOP { get; set; }
        public virtual ICollection<RECEIVECLAIM_DTA> RECEIVECLAIM_DTA { get; set; }
        public virtual ICollection<CLAIM_MEMBER_DTA> CLAIM_MEMBER_DTA { get; set; }
        public virtual ICollection<SERIAL> SERIAL { get; set; }
    }
}
