//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIM_MEMBER_CHANG7DAY
    {
        public CLAIM_MEMBER_CHANG7DAY()
        {
            this.CLAIMORDER_SHOP = new HashSet<CLAIMORDER_SHOP>();
        }
    
        public string SlpID { get; set; }
        public int SlpNo { get; set; }
        public string SlpSrlID { get; set; }
        public string SlpPrdID { get; set; }
        public string SlpLotNo { get; set; }
        public string SrlID { get; set; }
        public string PrdID { get; set; }
        public string LotNo { get; set; }
        public string CcmProp { get; set; }
        public string CcmStatus { get; set; }
        public System.DateTime CcmDate { get; set; }
    
        public virtual SELLPRODUCT_DTA_SERIA SELLPRODUCT_DTA_SERIA { get; set; }
        public virtual SERIAL SERIAL { get; set; }
        public virtual ICollection<CLAIMORDER_SHOP> CLAIMORDER_SHOP { get; set; }
    }
}
