//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLAIMORDER_SHOP
    {
        public CLAIMORDER_SHOP()
        {
            this.CLAIM_MEMBER_CHANG7DAY = new HashSet<CLAIM_MEMBER_CHANG7DAY>();
        }
    
        public string ClmID { get; set; }
        public string ClmNo { get; set; }
    
        public virtual CLAIMORDER_DTA CLAIMORDER_DTA { get; set; }
        public virtual ICollection<CLAIM_MEMBER_CHANG7DAY> CLAIM_MEMBER_CHANG7DAY { get; set; }
    }
}
