//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVER
    {
        public string EmpID { get; set; }
        public string SlpID { get; set; }
        public string DlvID { get; set; }
        public System.DateTime DlvDate { get; set; }
        public string DlvSerial { get; set; }
        public string DlvEnabled { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SELLPRODUCT SELLPRODUCT { get; set; }
    }
}
