//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.CLAIM_MEMBER = new HashSet<CLAIM_MEMBER>();
            this.CLAIMORDER = new HashSet<CLAIMORDER>();
            this.DELIVER = new HashSet<DELIVER>();
            this.EMPLOYEE_PHONE = new HashSet<EMPLOYEE_PHONE>();
            this.OFFER = new HashSet<OFFER>();
            this.ORDER_PRODUCT = new HashSet<ORDER_PRODUCT>();
            this.RECEIVECLAIM = new HashSet<RECEIVECLAIM>();
            this.RECEIVEORDER = new HashSet<RECEIVEORDER>();
        }
    
        public string EmpID { get; set; }
        public string PosID { get; set; }
        public string Idcard { get; set; }
        public string Email { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Address { get; set; }
        public string Sex { get; set; }
        public decimal Salary { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string EStatus { get; set; }
    
        public virtual ICollection<CLAIM_MEMBER> CLAIM_MEMBER { get; set; }
        public virtual ICollection<CLAIMORDER> CLAIMORDER { get; set; }
        public virtual ICollection<DELIVER> DELIVER { get; set; }
        public virtual POSITION POSITION { get; set; }
        public virtual ICollection<EMPLOYEE_PHONE> EMPLOYEE_PHONE { get; set; }
        public virtual ICollection<OFFER> OFFER { get; set; }
        public virtual ICollection<ORDER_PRODUCT> ORDER_PRODUCT { get; set; }
        public virtual ICollection<RECEIVECLAIM> RECEIVECLAIM { get; set; }
        public virtual ICollection<RECEIVEORDER> RECEIVEORDER { get; set; }
    }
}
