//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public MEMBER()
        {
            this.MEMBER_PHONE = new HashSet<MEMBER_PHONE>();
            this.SELLPRODUCT = new HashSet<SELLPRODUCT>();
        }
    
        public string MemID { get; set; }
        public string MFname { get; set; }
        public string MLname { get; set; }
        public string MAddress { get; set; }
        public string MSex { get; set; }
        public string MEmail { get; set; }
        public string MPassword { get; set; }
        public string MStatus { get; set; }
    
        public virtual ICollection<MEMBER_PHONE> MEMBER_PHONE { get; set; }
        public virtual ICollection<SELLPRODUCT> SELLPRODUCT { get; set; }
    }
}
