//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFFER
    {
        public OFFER()
        {
            this.OFFERDETAIL = new HashSet<OFFERDETAIL>();
        }
    
        public string OffID { get; set; }
        public string EmpID { get; set; }
        public string SupID { get; set; }
        public System.DateTime OffDate { get; set; }
        public string OffStatus { get; set; }
        public string OffEnabled { get; set; }
        public string EmpApprove { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
        public virtual ICollection<OFFERDETAIL> OFFERDETAIL { get; set; }
    }
}
