//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_PRODUCT
    {
        public ORDER_PRODUCT()
        {
            this.ORDER_PRODUCT_DTA = new HashSet<ORDER_PRODUCT_DTA>();
        }
    
        public string OrdID { get; set; }
        public string SupID { get; set; }
        public string EmpID { get; set; }
        public System.DateTime OrdDate { get; set; }
        public string OrdEnabled { get; set; }
        public decimal TotalCost { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ICollection<ORDER_PRODUCT_DTA> ORDER_PRODUCT_DTA { get; set; }
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
