//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_PRODUCT_DTA
    {
        public ORDER_PRODUCT_DTA()
        {
            this.RECEIVEORDER_DTA = new HashSet<RECEIVEORDER_DTA>();
        }
    
        public string OrdID { get; set; }
        public int OrdNo { get; set; }
        public string OffID { get; set; }
        public int OfdNo { get; set; }
        public int OrdAmount { get; set; }
    
        public virtual OFFERDETAIL OFFERDETAIL { get; set; }
        public virtual ORDER_PRODUCT ORDER_PRODUCT { get; set; }
        public virtual ICollection<RECEIVEORDER_DTA> RECEIVEORDER_DTA { get; set; }
    }
}
