//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public string SlpID { get; set; }
        public string BnkAccNumber { get; set; }
        public string PayNo { get; set; }
        public System.DateTime PayDate { get; set; }
        public decimal PayPrice { get; set; }
        public string PayImg { get; set; }
        public string PayEnabled { get; set; }
        public Nullable<decimal> PayPriceCheck { get; set; }
    
        public virtual BANK BANK { get; set; }
        public virtual SELLPRODUCT SELLPRODUCT { get; set; }
    }
}
