//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSITION
    {
        public POSITION()
        {
            this.EMPLOYEE = new HashSet<EMPLOYEE>();
            this.C_Roles = new HashSet<C_Roles>();
        }
    
        public string PosID { get; set; }
        public string DepID { get; set; }
        public string PosName { get; set; }
        public string PosEnabled { get; set; }
    
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        public virtual ICollection<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual ICollection<C_Roles> C_Roles { get; set; }
    }
}
