//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTLOT
    {
        public PRODUCTLOT()
        {
            this.SELLPRODUCT_DTA_NO_SERIA = new HashSet<SELLPRODUCT_DTA_NO_SERIA>();
            this.SERIAL = new HashSet<SERIAL>();
        }
    
        public string LotNo { get; set; }
        public string PrdID { get; set; }
        public string RecOID { get; set; }
        public int RecONo { get; set; }
        public int Amount { get; set; }
        public decimal Price { get; set; }
        public System.DateTime LotDate { get; set; }
        public string LotEnabled { get; set; }
        public int AmountRec { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual RECEIVEORDER_DTA RECEIVEORDER_DTA { get; set; }
        public virtual ICollection<SELLPRODUCT_DTA_NO_SERIA> SELLPRODUCT_DTA_NO_SERIA { get; set; }
        public virtual ICollection<SERIAL> SERIAL { get; set; }
    }
}
