//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIVECLAIM_DTA
    {
        public string RClmID { get; set; }
        public string RClmNo { get; set; }
        public int RClmAmount { get; set; }
        public string ClmID { get; set; }
        public string ClmNo { get; set; }
    
        public virtual CLAIMORDER_DTA CLAIMORDER_DTA { get; set; }
        public virtual RECEIVECLAIM RECEIVECLAIM { get; set; }
    }
}
