//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIVEORDER
    {
        public RECEIVEORDER()
        {
            this.RECEIVEORDER_DTA = new HashSet<RECEIVEORDER_DTA>();
        }
    
        public string RecOID { get; set; }
        public string EmpID { get; set; }
        public System.DateTime RecODate { get; set; }
        public string RecEnabled { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ICollection<RECEIVEORDER_DTA> RECEIVEORDER_DTA { get; set; }
    }
}
