//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIVECLAIM
    {
        public RECEIVECLAIM()
        {
            this.RECEIVECLAIM_DTA = new HashSet<RECEIVECLAIM_DTA>();
        }
    
        public string RClmID { get; set; }
        public System.DateTime RClmDate { get; set; }
        public string EmpID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual ICollection<RECEIVECLAIM_DTA> RECEIVECLAIM_DTA { get; set; }
    }
}
