//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELLPRODUCT_DTA
    {
        public SELLPRODUCT_DTA()
        {
            this.SELLPRODUCT_DTA_NO_SERIA = new HashSet<SELLPRODUCT_DTA_NO_SERIA>();
            this.SELLPRODUCT_DTA_SERIA = new HashSet<SELLPRODUCT_DTA_SERIA>();
        }
    
        public string SlpID { get; set; }
        public int SlpNo { get; set; }
        public string PrdID { get; set; }
        public int SpdAmount { get; set; }
        public decimal SpdPrice { get; set; }
        public Nullable<int> Discount { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual SELLPRODUCT SELLPRODUCT { get; set; }
        public virtual ICollection<SELLPRODUCT_DTA_NO_SERIA> SELLPRODUCT_DTA_NO_SERIA { get; set; }
        public virtual ICollection<SELLPRODUCT_DTA_SERIA> SELLPRODUCT_DTA_SERIA { get; set; }
    }
}
