//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELLPRODUCT_DTA_SERIA
    {
        public SELLPRODUCT_DTA_SERIA()
        {
            this.CLAIM_MEMBER_CHANG7DAY = new HashSet<CLAIM_MEMBER_CHANG7DAY>();
            this.CLAIM_MEMBER_DTA = new HashSet<CLAIM_MEMBER_DTA>();
        }
    
        public string SlpID { get; set; }
        public int SlpNo { get; set; }
        public string SrlID { get; set; }
        public string PrdID { get; set; }
        public string LotNo { get; set; }
    
        public virtual ICollection<CLAIM_MEMBER_CHANG7DAY> CLAIM_MEMBER_CHANG7DAY { get; set; }
        public virtual ICollection<CLAIM_MEMBER_DTA> CLAIM_MEMBER_DTA { get; set; }
        public virtual SELLPRODUCT_DTA SELLPRODUCT_DTA { get; set; }
        public virtual SERIAL SERIAL { get; set; }
    }
}
