//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELLPRODUCT
    {
        public SELLPRODUCT()
        {
            this.DELIVER = new HashSet<DELIVER>();
            this.PAYMENT = new HashSet<PAYMENT>();
            this.SELLPRODUCT_DTA = new HashSet<SELLPRODUCT_DTA>();
        }
    
        public string SlpID { get; set; }
        public string MemID { get; set; }
        public System.DateTime SlpDate { get; set; }
        public string FnameRec { get; set; }
        public string LnameRec { get; set; }
        public string AdressRec { get; set; }
        public string SlpStatus { get; set; }
        public decimal SlpSum { get; set; }
        public string SlpEnabled { get; set; }
    
        public virtual ICollection<DELIVER> DELIVER { get; set; }
        public virtual MEMBER MEMBER { get; set; }
        public virtual ICollection<PAYMENT> PAYMENT { get; set; }
        public virtual ICollection<SELLPRODUCT_DTA> SELLPRODUCT_DTA { get; set; }
    }
}
