//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELLPRODUCT_DTA_NO_SERIA
    {
        public string SlpID { get; set; }
        public int SlpNo { get; set; }
        public string PrdID { get; set; }
        public string LotNo { get; set; }
        public int Amount { get; set; }
    
        public virtual PRODUCTLOT PRODUCTLOT { get; set; }
        public virtual SELLPRODUCT_DTA SELLPRODUCT_DTA { get; set; }
    }
}
