//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIAL
    {
        public SERIAL()
        {
            this.CLAIM_MEMBER_CHANG7DAY = new HashSet<CLAIM_MEMBER_CHANG7DAY>();
            this.SELLPRODUCT_DTA_SERIA = new HashSet<SELLPRODUCT_DTA_SERIA>();
            this.CLAIMORDER_DTA = new HashSet<CLAIMORDER_DTA>();
        }
    
        public string SrlID { get; set; }
        public string PrdID { get; set; }
        public string LotNo { get; set; }
        public string SrlStatus { get; set; }
        public string ClmStatus { get; set; }
    
        public virtual ICollection<CLAIM_MEMBER_CHANG7DAY> CLAIM_MEMBER_CHANG7DAY { get; set; }
        public virtual PRODUCTLOT PRODUCTLOT { get; set; }
        public virtual ICollection<SELLPRODUCT_DTA_SERIA> SELLPRODUCT_DTA_SERIA { get; set; }
        public virtual ICollection<CLAIMORDER_DTA> CLAIMORDER_DTA { get; set; }
    }
}
