//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUPPLIER_PHONE
    {
        public string SupID { get; set; }
        public string Phone { get; set; }
        public Nullable<int> PhoneId { get; set; }
        public Nullable<bool> DeletePhone { get; set; }
    
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
