//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRADEMARK
    {
        public TRADEMARK()
        {
            this.BRAND = new HashSet<BRAND>();
        }
    
        public string TrdID { get; set; }
        public string TrdName { get; set; }
        public string TrdEnabled { get; set; }
    
        public virtual ICollection<BRAND> BRAND { get; set; }
    }
}
