//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThesisGamingStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPEPRODUCT
    {
        public TYPEPRODUCT()
        {
            this.PRODUCT = new HashSet<PRODUCT>();
        }
    
        public string TypeProductID { get; set; }
        public string TypeName { get; set; }
        public string TypeEnabled { get; set; }
    
        public virtual ICollection<PRODUCT> PRODUCT { get; set; }
    }
}
